### ISSUE TITLE
maj impossble avec DATEXPLORER.exe sur les fichiers *.DAT

### ISSUE THREAD

**Issue by Bhicham1977** [bentalebahmed/Citroen-Peugeot-RT6-car-radio-display-config-via-MiraScripts#1]
Bonjour,
Merci pour la procédure, 
moi aussi j'ai une C4 II 2014, j'avais le même soucis,
mais je n'ai pas pu mettre à jour les fichiers  .dat avec DATEXPLORER.exe...
heureusement , comme il y avait que des fichiers corrompus sur ma carte microSD , je l'ai sauvegardé sur mon ordinateur tous le contenu des trois partitions ....(le clone  est impossible dans ce cas )
j'ai suivi la procédure de l'installation du RT6 sur une nouvelle carte micro SD , voir : https://gpsmyway.pro-forum.fr/t162-firmwares-rt6-version-2-85-pour-emyway-et-wipnav-citroen-peugeot
je l'ai retiré et j'ai mis à jour  par tous les fichiers  des répertoire User_profile 
de l'ancienne carte SD (copie) vers  vers la nouvelle carte microSD...
et ça bien marché et j'ai repris les commande des boutons et le logos aussi 

![user_profile-RT6-C4](https://github.com/bentalebahmed/Citroen-Peugeot-RT6-car-radio-display-config-via-MiraScripts/assets/57708001/4574cbff-20b1-4e99-a9d9-4e946fac4485)

une fois tt est KO , je l'ai cloné cette fois  , en la sauvegardant en iso (comme ça je peut la restaurer si besoin sans refaire l'installation

**Comment by bentalebahmed** [comment]
D'après ce que j'ai compris, vous ne pouvez pas mettre à jour les fichiers .dat en utilisant DATEXPLORER.exe.

Pour ce faire, vous devez d'abord charger le fichier de configuration (.dat.cfg) en utilisant le deuxième bouton en haut à gauche (Load Config). Ensuite, utilisez le bouton Load DAT pour charger vos données (.dat). Maintenant, vous verrez toutes les informations sur la gauche sous forme de liste, cliquez sur l'équipe de la liste pour la voir dans le champ. 

Pour changer une valeur, double-cliquez, à droite vous pouvez la changer. Si vous ne pouvez pas changer une valeur, cela signifie qu'elle est verrouillée et que vous devez l'activer à partir du fichier .dat.cfg.

Après avoir modifié les valeurs, utilisez le bouton « Save» pour mettre à jour les données dans le fichier.
